name: ephys
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2024.11.26
  - libffi=3.4.4
  - openssl=3.0.15
  - pip=24.3.1
  - python=3.11.0
  - setuptools=75.1.0
  - sqlite=3.45.3
  - wheel=0.44.0
  - pip:
    - asttokens==3.0.0
    - backcall==0.2.0
    - cebra==0.4.0
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - colorama==0.4.6
    - comm==0.2.2
    - contourpy==1.1.1
    - cycler==0.12.1
    - debugpy==1.8.9
    - decorator==5.1.1
    - executing==2.1.0
    - filelock==3.16.1
    - fonttools==4.55.0
    - fsspec==2024.10.0
    - idna==3.10
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - ipykernel==6.29.5
    - ipython==8.12.3
    - jedi==0.19.2
    - jinja2==3.1.4
    - joblib==1.4.2
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - kiwisolver==1.4.7
    - literate-dataclasses==0.0.6
    - markupsafe==2.1.5
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.7
    - mpmath==1.3.0
    - nest-asyncio==1.6.0
    - networkx==3.1
    - numpy==1.26.4
    - opencv-python==4.8.1.78
    - packaging==24.2
    - pandas==2.0.3
    - parso==0.8.4
    - patsy==1.0.1
    - pickleshare==0.7.5
    - pillow==10.4.0
    - platformdirs==4.3.6
    - prompt-toolkit==3.0.48
    - psutil==6.1.0
    - pure-eval==0.2.3
    - pygments==2.18.0
    - pyparsing==3.0.9
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - pyzmq==26.2.0
    - requests==2.32.3
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.13.2
    - six==1.16.0
    - stack-data==0.6.3
    - statsmodels==0.14.1
    - sympy==1.13.3
    - threadpoolctl==3.5.0
    - torch==2.1.2
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - urllib3==2.2.3
    - wcwidth==0.2.13
    - zipp==3.20.2

